#pragma once
// HARDWARE

// DISPLAY
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define SCREEN_MONOCHROME 1
#define CS_PIN 10
#define DC_PIN 9
#define RST_PIN 8

// KEYBOARD
#define USE_MATRIX_KEYBOARD 1

#if USE_MATRIX_KEYBOARD
#define MATRIX_KEYBOARD_ROWS 4
#define MATRIX_KEYBOARD_COLS 4
#define COL_PINS {2, 3, 4, 5}
#define ROW_PINS {6, 7, 8, 9}

typedef enum key_t {
    // BUTTON_CE = 2, BUTTON_PERCENT, 
    // BUTTON_MRC, BUTTON_M_MINUS, BUTTON_M_PLUS, BUTTON_SQRT,
    BUTTON_SEVEN, BUTTON_EIGHT, BUTTON_NINE, BUTTON_DIVIDE,
    BUTTON_FOUR, BUTTON_FIVE, BUTTON_SIX, BUTTON_MULTIPLY,
    BUTTON_ONE, BUTTON_TWO, BUTTON_THREE, BUTTON_MINUS,
    BUTTON_ZERO, BUTTON_DOT, BUTTON_EQUAL, BUTTON_PLUS
} key_t;
#endif

#ifdef PLATFORM_SIM 
#include <raylib.h>

// bind raylib keys for simulator
// https://github.com/raysan5/raylib/blob/master/src/raylib.h#L576-L691
#define BUTTON_CE KEY_C
#define BUTTON_PERCENT KEY_P
#define BUTTON_MRC KEY_C
#define BUTTON_M_MINUS KEY_COMMA
#define BUTTON_M_PLUS KEY_PERIOD
#define BUTTON_SQRT KEY_S
#define BUTTON_SEVEN KEY_SEVEN
#define BUTTON_EIGHT KEY_EIGHT
#define BUTTON_NINE KEY_NINE
#define BUTTON_DIVIDE KEY_SLASH
#define BUTTON_FOUR KEY_FOUR
#define BUTTON_FIVE KEY_FIVE
#define BUTTON_SIX KEY_SIX
#define BUTTON_MULTIPLY KEY_X
#define BUTTON_ONE KEY_ONE
#define BUTTON_TWO KEY_TWO
#define BUTTON_THREE KEY_THREE
#define BUTTON_MINUS KEY_MINUS
#define BUTTON_ZERO KEY_ZERO
#define BUTTON_DOT KEY_D
#define BUTTON_EQUAL KEY_EQUAL
#define BUTTON_PLUS KEY_ENTER
#endif

#define USE_SERIAL_CONTROL 1

#if USE_SERIAL_CONTROL
#define KEYBOARD_SERIAL_FIRST_BYTE 'k'

#endif

#define USE_ANALOG_KEYBOARD 0
#define MAX_KEYS_PRESSED 4
// #define POWER_PIN 

// UI
#define ENABLE_DOCK 1
#define DOCK_WIDTH 43
#define MENU_ELEMENT_HEIGHT 5
#define NODE_AUTO_PADDING 3