#pragma once
// HARDWARE

// DISPLAY
#define USE_DISPLAY 1
#define DISPLAY_WIDTH 170
#define DISPLAY_HEIGHT 320
#define DISPLAY_ROTATION  0
#define DISPLAY_COLOR_DEPTH 16
#define DISPLAY_CS_PIN 15
#define DISPLAY_DC_PIN 14
#define DISPLAY_RST_PIN 16

#define SIM_DISPLAY_WIDTH 320
#define SIM_DISPLAY_HEIGHT 170

// DISPLAY MODEL (UNCOMMENT ONE)
// #define USE_DISPLAY_ST7565
#define USE_DISPLAY_ST7789

// KEYBOARD
#define USE_MATRIX_KEYBOARD 1

#if USE_MATRIX_KEYBOARD
#define MATRIX_KEYBOARD_ROWS 4
#define MATRIX_KEYBOARD_COLS 4
#define COL_PINS {3, 4, 5, 6}
#define ROW_PINS {7, 8, 9, 10}

// typedef enum {
//     // BUTTON_CE = 2, BUTTON_PERCENT, 
//     // BUTTON_MRC, BUTTON_M_MINUS, BUTTON_M_PLUS, BUTTON_SQRT,
//     BUTTON_SEVEN, BUTTON_EIGHT, BUTTON_NINE, BUTTON_DIVIDE,
//     BUTTON_FOUR, BUTTON_FIVE, BUTTON_SIX, BUTTON_MULTIPLY,
//     BUTTON_ONE, BUTTON_TWO, BUTTON_THREE, BUTTON_MINUS,
//     BUTTON_ZERO, BUTTON_DOT, BUTTON_EQUAL, BUTTON_PLUS
// } calc_key_t;

typedef enum {
    BUTTON_ONE, BUTTON_TWO, BUTTON_THREE, BUTTON_A,
    BUTTON_FOUR, BUTTON_FIVE, BUTTON_SIX, BUTTON_B,
    BUTTON_SEVEN, BUTTON_EIGHT, BUTTON_NINE, BUTTON_C,
    BUTTON_MULTIPLY, BUTTON_ZERO, BUTTON_HASHTAG, BUTTON_D
} calc_key_t;
#endif

#define BUTTON_UP BUTTON_EIGHT
#define BUTTON_DOWN BUTTON_TWO
#define BUTTON_LEFT BUTTON_FOUR
#define BUTTON_RIGHT BUTTON_SIX
#define BUTTON_OK BUTTON_FIVE

#ifdef PLATFORM_SIM 
#include <raylib.h>

// bind raylib keys for simulator
// https://github.com/raysan5/raylib/blob/master/src/raylib.h#L576-L691
#define BUTTON_CE KEY_C
#define BUTTON_PERCENT KEY_P
#define BUTTON_MRC KEY_C
#define BUTTON_M_MINUS KEY_COMMA
#define BUTTON_M_PLUS KEY_PERIOD
#define BUTTON_SQRT KEY_S
#define BUTTON_SEVEN KEY_SEVEN
#define BUTTON_EIGHT KEY_EIGHT
#define BUTTON_NINE KEY_NINE
#define BUTTON_DIVIDE KEY_SLASH
#define BUTTON_FOUR KEY_FOUR
#define BUTTON_FIVE KEY_FIVE
#define BUTTON_SIX KEY_SIX
#define BUTTON_MULTIPLY KEY_X
#define BUTTON_ONE KEY_ONE
#define BUTTON_TWO KEY_TWO
#define BUTTON_THREE KEY_THREE
#define BUTTON_MINUS KEY_MINUS
#define BUTTON_ZERO KEY_ZERO
#define BUTTON_DOT KEY_D
#define BUTTON_EQUAL KEY_EQUAL
#define BUTTON_PLUS KEY_ENTER
#endif

#define MAX_KEYS_PRESSED 4 

// UI
#define ENABLE_DOCK 1
#define DOCK_WIDTH 60
#define MENU_ELEMENT_HEIGHT 5

// SIMULATOR
#define SIM_UART 1
